apiVersion: v1
kind: Service
metadata:
  name: thumbor-prod
  labels:
    app: thumbor-prod
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: thumbor-prod
    name: thumbor-prod
  selector:
    app: thumbor-prod

